### ISSUE TITLE
Mob hats lag

### ISSUE THREAD

**Issue by kikugie** [WerDei/Server-Hats#2]
Mobs picking up items as hats naturally don't despawn. If some common item is allowed as a hat there might be a lot of persistent mobs. Example: glow ink sac is allowed as ha hat, glow squids die in lush caves, zombies and skeletons pick up sacs and never despawn.

- Suggestion: make separate list for items allowed for mob hats or make mobs equip items as hats only via dispenser.

**Comment by WerDei** [comment]
This is a vanilla issue, unfortunately. Mobs only equip items as hats after they pick them up first. If they can't equip it, they'd just hold an item in their hand, which would still prevent them from despawning.

Note that since 1.17.1 zombies/drowned/etc can't pick up glow ink sacks at all, which also prevents them from equipping them.
I just tested this - mob does not pick up the glow ink sack, and doesn't equip it either.

Mojang are looking into a more permanent solution (see https://twitter.com/kingbdogz/status/1460241959503736833), but it likely won't be implemented at least until 1.19.

As a side note, if you use at least mod version 0.7 and set "mobsCanEquipHats" to false, mobs will no longer attempt to equip items on their heads (but you can still use a dispenser to equip them manually, similarly to your suggestion).
